### ISSUE TITLE
Would you be interested in submitting this repo to flatpak?

### ISSUE THREAD

**Issue by xplshn** [nhubaotruong/mercury-flatpak#1]
If so, please tell me how the project is structured, what patches, if any, have you had to do and what functionality of the browser is limited because of the sandbox, the process to get this in Flathub is fairly easy, but you will have to comply with their security police which is rather strict...

If the program gets on Flathub, would you be able to co own the repo with me? As I am rather busy with school.

**Comment by nhubaotruong** [comment]
@xplshn Hi, I'm currently not using Mercury browser as the main developer seems to prioritize Thorium over Mercury. It wouldn't make sense for me to maintain if I'm not actively using it.

You're free to take the code though. I mostly based it on librewolf. I've also setup flatpak-external-resource checker attributes. So flathub bot should create PR for new version for you (I haven't tested it though)

**Comment by xplshn** [comment]
Okay then - I don't know if I will though. I can't promise anything. But, if I fork your repo you wouldn't mind right?

**Comment by nhubaotruong** [comment]
@xplshn Yeah sure, please fork it, I'm posting it on github to share :smiley_cat:
